Fix issue underlined in https://github.com/updatecli/updatecli/pull/176\#issuecomment-779336181
With the following configuration:

```
source:
  name: Get Latest mirrorbits release version
  kind: githubRelease
  spec:
    owner: "etix"
    repository: "mirrorbits"
    token: {{ requiredEnv "CUSTOM_GH_TOKEN" }}
    username: dduportal
    version: latest
conditions:
  isENVSet:
    name: Is the 2nd ENV instruction having a "keyword" set to "MIRRORBIT_VERSION"
    kind: dockerfile
    spec:
      file: Dockerfile
      Instruction: "ENV[0][0]"
      Value: "MIRRORBITS_VERSION"
    scm:
      github:
        user: "olblak"
        email: "updatecli@olblak.com"
        owner: "olblak"
        repository: "mirrorbits"
        token: {{ requiredEnv "CUSTOM_GH_TOKEN" }}
        username: "olblak"
        branch: "master"

```

the result of the command line `./bin/updateCli diff --config ./bin/config.yml.tpl` is:

```
DIFF

+++++++++++
+ PREPARE +
+++++++++++

Cloning git repository: https://github.com/olblak/mirrorbits.git in /var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/olblak/mirrorbits
Enumerating objects: 99, done.
Counting objects: 100%!((MISSING)99/99), done.
Compressing objects: 100%!((MISSING)72/72), done.
Total 99 (delta 43), reused 62 (delta 21), pack-reused 0
Fetching remote branches

+++++++
+ RUN +
+++++++

SOURCE:
=======

✔ 'latest' github release version founded: v0.5.1

CHANGELOG:
==========

Release published on the 2018-11-23 12:25:27 +0000 UTC at the url https://github.com/etix/mirrorbits/releases/tag/v0.5.1

- Sort the mirrors by the last state date in the list command

- Regression: mirrors were not able to transition between up and down states

CONDITIONS:
===========

🐋 On (Docker)file "/var/folders/2s/09szbrgn22l2tcvxz1_k34g40000gn/T/updatecli/olblak/mirrorbits/Dockerfile":

✗ Instruction "ENV[0][0]" found but incorrectly set to "MIRRORBIT_VERSION" instead of "MIRRORBITS_VERSION"

=============================

REPORTS:

✗ CONFIG.YML
        Source:
                ✔  Get Latest mirrorbits release version(githubRelease)
        Condition:
                ✔  Is the 2nd ENV instruction having a "keyword" set to "MIRRORBIT_VERSION"(dockerfile)
        Target:

ERROR: ✗ 1/1 job(s) failed
ERROR: command failed
```

Signed-off-by: Damien Duportal <damien.duportal@gmail.com>